// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyAw6CFKX3nww0_-rZNUUQ5v1u5EwuDottw',
      appId: '1:961146710046:android:ab8e6d55eae748ff29660f',
      messagingSenderId: '961146710046',
      projectId: 'todo-pomme',
      storageBucket: 'todo-pomme.appspot.com',
      databaseURL:
          'https://todo-pomme-default-rtdb.europe-west1.firebasedatabase.app');

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyDFJkX6Q17M4ZmeKRXhgERY2VDa1x3YHkE',
      appId: '1:961146710046:ios:42d13c9d4526444329660f',
      messagingSenderId: '961146710046',
      projectId: 'todo-pomme',
      storageBucket: 'todo-pomme.appspot.com',
      iosClientId:
          '961146710046-au99omlugt3kedoho7g1ct3jd929gq60.apps.googleusercontent.com',
      iosBundleId: 'fr.oxypomme.todoPomme',
      databaseURL:
          'https://todo-pomme-default-rtdb.europe-west1.firebasedatabase.app');
}
